language: node_js

# test on different versions of node.js
node_js:
    - 6.11.1
    - 8.1.4

# configure notifications
notifications:
    email:
        recipients:
          - maurizio.cescon@gmail.com
        on_success: change # default: change
        on_failure: always # default: always
